[package]
name = "jati"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.0.0"
nalgebra = "0.31"
approx = "0.5"
anyhow = "1.0.0"
rstest = "0.16.0"
rand = "0.8"
pest = "2.5.7"
pest_derive = "2"