name: Build and release installers

on:
  push:
    branches: [main]
  release:
    types: [published]


    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install packaging tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          cargo install cargo-deb
          cargo install cargo-rpm

      - name: Install packaging tools (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo install cargo-wix

      - name: Run tests
        run: |
          cargo test --release --bin jati; cargo test --release --bin jati-parallel --features "parallel"

      - name: Build release binary
        run: cargo build --release --bin jati; cargo build --release --bin jati-parallel --features "parallel"

      # Strip release binary (Linux and macOS)
      - name: Strip release binary (Linux/macOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: strip target/release/jati; strip target/release/jati-parallel

      # Linux: Package .deb and .rpm
      - name: Package as .deb (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo deb --no-build --install target/release/jati; cargo deb --no-build --install target/release/jati-parallel --features "parallel"
        shell: bash

      # Windows: Package as .msi
      - name: Prepare WiX (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo wix init || true

      - name: Package as .msi (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cargo wix --no-build --bin-path target/release/jati; cargo wix --no-build --bin-path target/release/jati-parallel --features "parallel"
        shell: pwsh

      # MacOS: Zip binary
      - name: Zip release binary (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          zip -j target/release/jati-macos.zip target/release/jati; zip -j target/release/jati-parallel-macos.zip target/release/jati-parallel
        shell: bash

      # Collect artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installers
          path: |
            target/debian/*.deb
            target/rpmbuild/RPMS/x86_64/*.rpm
            target/wix/*.msi
            target/release/*.exe
            target/release/${BINARY_NAME}*-macos.zip
            target/release/${BINARY_NAME}*

      # Attach to release if this is a release build
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/debian/*.deb
            target/rpmbuild/RPMS/x86_64/*.rpm
            target/wix/*.msi
            target/release/*.exe
            target/release/${BINARY_NAME}-macos.zip
            target/release/${BINARY_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
